llm:
  model_name: Qwen3-8B
  api_key: not-needed
  api_url: http://0.0.0.0:8000/v1
  temperature: 0.6
  max_tokens: 32768
  max_workers: 64
  enable_thinking: false
  system_prompt: ""

judge:
  model_name: Qwen3-8B
  api_key: not-needed
  api_url: http://0.0.0.0:8000/v1
  temperature: 0.0
  max_tokens: 4096
  system_prompt: ""
  enable_thinking: false
  # 是否使用 LLM judge（如果为 True，会加载 judge_client 并用于评估）
  use_llm_judge: false

repeats: 1
max_samples: 100
datasets_path: datasets
results_path: results
